font:
 size: 13.0
 normal:
   family: 'BitstreamVeraSansMono Nerd Font'
 bold:
   family: 'BitstreamVeraSansMono Nerd Font'
 italic:
   family: 'BitstreamVeraSansMono Nerd Font'
 bold_italic:
   family: 'BitstreamVeraSansMono Nerd Font'
key_bindings:
 - { key: N, mods: Control|Shift, action: SpawnNewInstance }
